# -*- coding: utf-8 -*-
"""operators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1heNt10vpmejD7ecd8WgUdtjB_xlH6zp5
"""

a = 7
b = 2
print ('Arithmetic Operations')
print ('Sum: ', a + b)
print ('Subtraction: ', a - b)
print ('Multiplication: ', a * b)
print ('Division: ', a / b)
print ('Floor Division: ', a // b)
print ('Modulo: ', a % b)
print ('Power: ', a ** b)

a = 10
b = 5
a += b      # a = a + b
print(a)

a = 5
b = 2
print('Comparison operators')
print('a == b =', a == b)
print('a != b =', a != b)
print('a > b =', a > b)
print('a < b =', a < b)
print('a >= b =', a >= b)
print('a <= b =', a <= b)

a = 5
b = 6
print((a > 2) and (b >= 6))
print((a > 6) or (b > 7))

x1 = 5
y1 = 5
x2 = 'Hello'
y2 = 'Hello'
x3 = [1,2,3]
y3 = [1,2,3]
print(x1 is not y1)
print(x2 is y2)
print(x3 is y3)

x = 'Hello world'
print('H' in x)
print('hello' not in x)